### ISSUE TITLE
Use IronPython to parse palettes from SwatchBooker

### ISSUE THREAD

**Issue by x-a-n-a-x** [cyotek/Cyotek.Windows.Forms.ColorPicker#11]
Hello

Have you ever thought of using http://ironpython.net to reuse code from [SwatchBooker](https://github.com/olivierberten/SwatchBooker) and parse its different files formats ?

I am not a developer but I've heard IronPython can be used in C# projects.

Feel free to close this issue if it's not relevant.

**Comment by cyotek** [comment]
Hello,

Thanks for the suggestion. As SwatchBooker uses XML for its palette files, there's no need for me to get exotic, I can read them natively without needing to use any additional libraries.

Regards;
Richard Moss
