### ISSUE TITLE
Color of the bar for value L is not changing.

### ISSUE THREAD

**Issue by sheitmann** [cyotek/Cyotek.Windows.Forms.ColorPicker#6]
I compared some color selectors and I mentioned that you bar for value L is not changing it's color.
If you use for example Paint-NET you see that the bar for the V value (I know L is not V but that doesn't matter in that case) is changing it's color matching to what color you would get if you move the slider on it.
Yours is always black to white in gray scale but if I have a red tone it should be black to white in a red gradient. .

**Comment by cyotek** [comment]
I see what you mean - thanks. If no-one else submits a PR I'll get it corrected in the next update.
