### ISSUE TITLE
Color wheel jumps a lot in ColorEditManager Component Demonstration

### ISSUE THREAD

**Issue by sheitmann** [cyotek/Cyotek.Windows.Forms.ColorPicker#7]
When I move the S slider the color marker of the wheel sometimes jumps around, same when using the L slider.
Do you bound the end color to the wheel?
Usually the wheel is only attached to the H and S slider and L is ignored. Also L is often not even set if you change the color selector in the wheel. On your example it is always set to 50 which is annoying.

For example take a look how Pain.NET color picker behaves and you see what I mean.

**Comment by cyotek** [comment]
Thanks for this report too. I've had a play and I think I see what you mean. I suspect this is the same as #5. I've got the source for a really old version of Paint.NET somewhere - I'll take a look at some point and see how this deals with colour space conversion.
