### ISSUE TITLE
how to compile ?

### ISSUE THREAD

**Issue by pc8181** [cyotek/Cyotek.Windows.Forms.ColorPicker#8]
![image](https://user-images.githubusercontent.com/13380400/28018694-e876dc2a-659b-11e7-82f3-a039f0b6a994.png)

**Comment by cyotek** [comment]
Hello,

That is [interpolated strings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interpolated-strings), a new feature of C# 6. You'd need to be using Visual Studio 2015 or higher.

To fix for your version of Visual Studio, replace

```c#
$"{this.Color.R:X2}{this.Color.G:X2}{this.Color.B:X2}"
```

with

```c#
string.Format("{0:X2}{1:X2}{2:X2}", this.Color.R, this.Color.G, this.Color.B)
```

Or, grab the latest source - I reverted that particular change.

Regards;
Richard Moss
